# ============================================================
# AI DATA ANALYST - TOOLS
# ============================================================

import os
import pandas as pd


# ============================================================
# TOOL 1: INSPECT DATASET
# ============================================================

def inspect_dataset(df):
    """
    Inspect the dataset and return useful metadata.
    """

    return {
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "column_names": df.columns.tolist(),
        "data_types": {
            column: str(dtype)
            for column, dtype in df.dtypes.items()
        }
    }


# ============================================================
# TOOL 2: EXECUTE PYTHON ANALYSIS
# ============================================================

def execute_analysis(code, df):
    """
    Execute AI-generated pandas/Python analysis code.

    The AI-generated code should store its final answer
    inside a variable called `result`.
    """

    try:

        # Environment available to generated code
        local_variables = {
            "df": df,
            "pd": pd
        }

        # Execute generated Python code
        exec(code, {}, local_variables)

        # Get result generated by AI
        result = local_variables.get("result")

        if result is None:

            return {
                "success": True,
                "type": "text",
                "result": "Analysis executed successfully, but no result variable was created."
            }

        # ----------------------------------------------------
        # DataFrame result
        # ----------------------------------------------------

        if isinstance(result, pd.DataFrame):

            # Convert DataFrame into JSON-safe structure
            return {
                "success": True,
                "type": "dataframe",
                "columns": result.columns.tolist(),
                "rows": result.to_dict(orient="records")
            }

        # ----------------------------------------------------
        # Series result
        # ----------------------------------------------------

        if isinstance(result, pd.Series):

            result_df = result.reset_index()

            return {
                "success": True,
                "type": "dataframe",
                "columns": result_df.columns.tolist(),
                "rows": result_df.to_dict(orient="records")
            }

        # ----------------------------------------------------
        # Dictionary result
        # ----------------------------------------------------

        if isinstance(result, dict):

            return {
                "success": True,
                "type": "dictionary",
                "result": result
            }

        # ----------------------------------------------------
        # List result
        # ----------------------------------------------------

        if isinstance(result, list):

            return {
                "success": True,
                "type": "list",
                "result": result
            }

        # ----------------------------------------------------
        # Normal value
        # ----------------------------------------------------

        return {
            "success": True,
            "type": "value",
            "result": result
        }

    except Exception as e:

        return {
            "success": False,
            "type": "error",
            "error": str(e)
        }


# ============================================================
# TOOL 3: GENERATE VISUALIZATION
# ============================================================

def generate_visualization(
    code,
    df,
    output_path="outputs/chart.png"
):
    """
    Execute AI-generated matplotlib visualization code.

    IMPORTANT:
    The AI only creates the figure.
    This function is responsible for saving the figure.
    """

    import matplotlib

    # Use non-GUI backend
    matplotlib.use("Agg")

    import matplotlib.pyplot as plt

    try:

        # ----------------------------------------------------
        # Create output directory
        # ----------------------------------------------------

        output_directory = os.path.dirname(output_path)

        if output_directory:
            os.makedirs(
                output_directory,
                exist_ok=True
            )

        # ----------------------------------------------------
        # Remove old figures
        # ----------------------------------------------------

        plt.close("all")

        # ----------------------------------------------------
        # Environment available to AI-generated code
        # ----------------------------------------------------

        local_variables = {
            "df": df,
            "pd": pd,
            "plt": plt
        }

        # ----------------------------------------------------
        # Execute visualization code
        # ----------------------------------------------------

        exec(
            code,
            {},
            local_variables
        )

        # ----------------------------------------------------
        # Check if figure exists
        # ----------------------------------------------------

        figure_numbers = plt.get_fignums()

        if not figure_numbers:

            return {
                "success": False,
                "type": "visualization",
                "error": (
                    "Visualization code executed successfully "
                    "but did not create a matplotlib figure."
                )
            }

        # ----------------------------------------------------
        # Get current figure
        # ----------------------------------------------------

        figure = plt.gcf()

        # ----------------------------------------------------
        # Save figure
        # ----------------------------------------------------

        figure.savefig(
            output_path,
            bbox_inches="tight",
            dpi=150
        )

        # ----------------------------------------------------
        # Verify file exists
        # ----------------------------------------------------

        if not os.path.exists(output_path):

            return {
                "success": False,
                "type": "visualization",
                "error": "Chart was not created successfully."
            }

        # ----------------------------------------------------
        # Close figures
        # ----------------------------------------------------

        plt.close("all")

        return {
            "success": True,
            "type": "visualization",
            "path": output_path
        }

    except Exception as e:

        plt.close("all")

        return {
            "success": False,
            "type": "visualization",
            "error": str(e)
        }