from python_executor import execute_python


def inspect_dataset(df):
    """
    Inspect the structure of the dataset.
    """

    result = {
        "rows": len(df),
        "columns": len(df.columns),
        "column_names": df.columns.tolist(),
        "data_types": {
            column: str(dtype)
            for column, dtype in df.dtypes.items()
        },
        "missing_values": {
            column: int(value)
            for column, value in df.isnull().sum().items()
        }
    }

    return result


def execute_analysis(code, df):
    """
    Execute Python analysis generated by the LLM.
    """

    result = execute_python(
        code,
        df
    )

    return result